version: 2
jobs:
  test:
    docker:
      - image: circleci/python:3.6.5
    environment:
      PIPENV_VENV_IN_PROJECT: true
    steps:
      - checkout
      - restore_cache:
          key: v1-py-cache-{{ .Branch }}-{{ checksum "Pipfile.lock" }}
      - run:
          name: Install requirements
          command: |
            pipenv install
      - save_cache:
          name: Save Python dependencies cache
          key: v1-py-cache-{{ .Branch }}-{{ checksum "Pipfile.lock" }}
          paths:
            - ~/.venv
      - run:
          name: Run tests
          command: pipenv run pytest
            
workflows:
  version: 2
  build_and_test:
    jobs:
      - test:
          filters:
            tags:
              only: /^v.*/
