version: 2
jobs:
  test:
    docker:
      - image: preethamkamidi/verifytweet-base:latest
    steps:
      - checkout
      - restore_cache:
          key: v1-py-cache-{{ .Branch }}-{{ checksum "requirements-dev.txt" }}-{{ checksum "requirements.txt" }}
      - run:
          name: Setup venv and install requirements
          command: |
            python3 -m venv ~/.venv
            echo ". ~/.venv/bin/activate" >> $BASH_ENV
            source $BASH_ENV
            pip install -r requirements.txt -r requirements-dev.txt
      - save_cache:
          name: Save Python dependencies cache
          key: v1-py-cache-{{ .Branch }}-{{ checksum "requirements-dev.txt" }}-{{ checksum "requirements.txt" }}
          paths:
            - ~/.venv
      - run:
          name: Run tests
          command: pytest
            
workflows:
  version: 2
  build_and_test:
    jobs:
      - test:
          filters:
            tags:
              only: /^v.*/
            branches:
              only:
                - master
                - develop
