version: 2
jobs:
  build:
    machine:
      image: ubuntu-1604:201903-01
      docker_layer_caching: true
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: |
            echo 'export TAG=$(grep -oE "\"(.*?)\"" verifytweet/__init__.py)' >> $BASH_ENV
            echo 'export TAG=${TAG:1:5}' >> $BASH_ENV
            echo 'export IMAGE_NAME=verifytweet' >> $BASH_ENV
      - run:
          name: Build and push Docker image
          command: |
            docker build -t preethamkamidi/$IMAGE_NAME:$TAG .
            echo $DOCKER_PWD | docker login -u $DOCKER_USER --password-stdin
            docker push preethamkamidi/$IMAGE_NAME:$TAG
workflows:
  version: 2
  build_and_push:
    jobs:
      - build:
          filters:
            tags:
              only: /^v.*/
